<a href="https://colab.research.google.com/github/changhong-yang/testing-scripts/blob/main/Pytorch/Build_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torchvision
from torchvision import transforms, datasets

# Download the datasets and put them into the dataloaders

train = datasets.MNIST('', train=True, download=True,
                       transform=transforms.Compose([
                           transforms.ToTensor()
                       ]))

test = datasets.MNIST('', train=False, download=True,
                       transform=transforms.Compose([
                           transforms.ToTensor()
                       ]))

trainset = torch.utils.data.DataLoader(train, batch_size=10, shuffle=True)
testset = torch.utils.data.DataLoader(test, batch_size=10, shuffle=False)

  0%|          | 0/9912422 [00:00<?, ?it/s]

Extracting MNIST/raw/train-images-idx3-ubyte.gz to MNIST/raw



  0%|          | 0/28881 [00:00<?, ?it/s]

Extracting MNIST/raw/train-labels-idx1-ubyte.gz to MNIST/raw



  0%|          | 0/1648877 [00:00<?, ?it/s]

Extracting MNIST/raw/t10k-images-idx3-ubyte.gz to MNIST/raw



  0%|          | 0/4542 [00:00<?, ?it/s]

Extracting MNIST/raw/t10k-labels-idx1-ubyte.gz to MNIST/raw



In [2]:
# set up Neural Network Architecture

import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):

    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(28*28, 64)
        self.fc2 = nn.Linear(64, 64)
        self.fc3 = nn.Linear(64, 64)
        self.fc4 = nn.Linear(64, 10)
      
    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = F.relu(self.fc3(x))
        x = self.fc4(x)
        return F.log_softmax(x, dim=1)

net = Net()
print(net)

Net(
  (fc1): Linear(in_features=784, out_features=64, bias=True)
  (fc2): Linear(in_features=64, out_features=64, bias=True)
  (fc3): Linear(in_features=64, out_features=64, bias=True)
  (fc4): Linear(in_features=64, out_features=10, bias=True)
)


In [5]:
# set up the input

X = torch.randn((28,28))
X

tensor([[ 0.4648, -1.0912, -0.5738, -1.3530, -0.2926, -0.4387, -2.7983,  1.7623,
         -0.8593,  0.5277, -2.6658, -0.2102, -0.4147, -0.3597, -1.0477,  0.2768,
         -0.4200,  0.5081, -1.0633,  0.3585, -0.6596, -0.4714,  0.5702,  0.4250,
         -0.7163, -0.0383,  1.7437,  1.0447],
        [ 1.5573, -1.8223, -1.1876,  0.4924,  1.5866, -0.5258,  0.8955, -0.2970,
          0.1866, -0.3228, -0.2971, -0.7797,  1.4894, -0.9237, -2.0037, -0.4038,
          0.9243, -1.0899,  0.8111,  1.1980,  0.8430,  0.6677,  1.5861,  0.2792,
         -0.8820,  1.0738,  0.1762, -0.4503],
        [-0.3834,  0.8371,  0.0414, -0.1181, -0.3395,  0.0818,  0.5528,  1.1141,
         -0.3826, -0.6883, -0.1908, -0.2721,  0.4130,  0.2317,  0.7921,  0.8611,
          0.7099, -0.2328, -0.2179, -1.8152,  0.4580,  1.1528,  1.1482, -1.2098,
          0.8906,  0.5931,  2.0116,  0.7471],
        [ 0.7622, -1.1502,  0.1411, -0.6013,  0.5312,  1.5880, -0.2019,  2.3372,
          0.3279,  0.9436, -1.2784,  1.2477,  0.6786

In [6]:
# reshape X

X = X.view(-1,28*28)
X

tensor([[ 0.4648, -1.0912, -0.5738, -1.3530, -0.2926, -0.4387, -2.7983,  1.7623,
         -0.8593,  0.5277, -2.6658, -0.2102, -0.4147, -0.3597, -1.0477,  0.2768,
         -0.4200,  0.5081, -1.0633,  0.3585, -0.6596, -0.4714,  0.5702,  0.4250,
         -0.7163, -0.0383,  1.7437,  1.0447,  1.5573, -1.8223, -1.1876,  0.4924,
          1.5866, -0.5258,  0.8955, -0.2970,  0.1866, -0.3228, -0.2971, -0.7797,
          1.4894, -0.9237, -2.0037, -0.4038,  0.9243, -1.0899,  0.8111,  1.1980,
          0.8430,  0.6677,  1.5861,  0.2792, -0.8820,  1.0738,  0.1762, -0.4503,
         -0.3834,  0.8371,  0.0414, -0.1181, -0.3395,  0.0818,  0.5528,  1.1141,
         -0.3826, -0.6883, -0.1908, -0.2721,  0.4130,  0.2317,  0.7921,  0.8611,
          0.7099, -0.2328, -0.2179, -1.8152,  0.4580,  1.1528,  1.1482, -1.2098,
          0.8906,  0.5931,  2.0116,  0.7471,  0.7622, -1.1502,  0.1411, -0.6013,
          0.5312,  1.5880, -0.2019,  2.3372,  0.3279,  0.9436, -1.2784,  1.2477,
          0.6786,  0.9401, -

In [9]:
# Going through the network

output = net(X)
output

tensor([[-2.2257, -2.3481, -2.3598, -2.2916, -2.3032, -2.4583, -2.4208, -2.1664,
         -2.2285, -2.2608]], grad_fn=<LogSoftmaxBackward0>)