<a href="https://colab.research.google.com/github/changhong-yang/testing-scripts/blob/main/Pytorch/Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
# create some Tensors

x = torch.Tensor([5,3])
y = torch.Tensor([2,1])

In [3]:
# tensor multiplication

print(x*y)

tensor([10.,  3.])


In [4]:
# similar operation in numpy

# zeros
x = torch.zeros([2,5])
print(x)

# shape
print(x.shape)

# random
y = torch.rand([2,5])
print(y)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
torch.Size([2, 5])
tensor([[0.1564, 0.7261, 0.1114, 0.0305, 0.2137],
        [0.4125, 0.7845, 0.3901, 0.1034, 0.5467]])


In [5]:
# tensor reshape
y.view([1,10])

tensor([[0.1564, 0.7261, 0.1114, 0.0305, 0.2137, 0.4125, 0.7845, 0.3901, 0.1034,
         0.5467]])

In [6]:
# view() does not modify the tensor
y

tensor([[0.1564, 0.7261, 0.1114, 0.0305, 0.2137],
        [0.4125, 0.7845, 0.3901, 0.1034, 0.5467]])